[Variables]
Version=1.1
MainLanguage=English


ScaleDpi=1
ThemeFont=Segoe UI

FontScale=100
ColorBar=0,0,0
ColorActiveBar=255,255,255
ColorLine=255,255,255
ColorFont=255,255,255
FontFace=Segoe UI Light
FontFaceClock=Segoe UI Light
FontFaceDate=Segoe UI

OpacityBar=15
OpacityActiveBar=30
OpacityLine=255
OpacityFont=255
OpacityFont1=80
OpacityFont2=150
AnalogClockSize=150
LineWidth=3
HideClock=0
HideDate=0
HideTasks=0
UseBlur=0
AnalogueClock=0

HideAnalogClock=1

HideBigText=0
ChunkNumbers=1
ChunkTimes=1
12HourSubstitute="^(\d)$":"0\0","13":"1","14":"2","15":"3","16":"4","17":"5","18":"6","19":"7","20":"8","21":"9","22":"10","23":"11","24":"00","25":"01","26":"02","27":"03","28":"04","29":"05","30":"06","31":"07","32":"08"
24HourSubstitute=^(\d)$":"0\0","24":"00","25":"01","26":"02","27":"03","28":"04","29":"05","30":"06","31":"07","32":"08"
Use12Hour=1
DarkMode=0
ttgallerystyle=dark
OnOff=
CornerRadius=8
BorderOutline=130,130,130,100
WindowColor=25,25,25
HideUnits=1
DisplayAMPM=1
TimeFormat=%H:%M
HourFormat=%H
HideWeekMode=1

PlayDing=0
Segments=10
SegmentDuration=90
Padding=2
BarPadding=0
DayStartHour=7
DayStartMinute=30
DayEndHour=23
DayEndMinute=00
clockPositionY=65
ClockOffset=30
DisableHighlight=0
SegmentColor=0,0,0,50
HighlightColor=255,255,255,40
ClockColor=255,255,255
NumbersFontColor=255,255,255,100
TimesFontColor=255,255,255,50
Blur=None
SoundFile=#@#\Sound\sound.wav
PlaySound=1
Debug=1
MinutesOverride=40
HoursOverride=11

12H=0
Hidesis=0
BigTaskTextSize=150
LetMeStyleIt=0
UseWallpaper=1

DisableClearTaskAtEnd=1
ChunkNumbersPadding=60


[Default]
FontColor=#textcolor2#
FontFace=#ThemeFont#
FontSize=(11)*#scaledpi#
StringAlign=LEFT
AntiAlias=1
